openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.0
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /counter:
    get:
      summary: Returns a current count
      operationId: fetchCount
      tags:
        - counter
      responses:
        "200": # status code
          description: Returns a current count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: "integer"
                    format: "int64"
                    example: 1
                required:
                  - count
  /user:
    get:
      summary: Returns a list of users.
      tags:
        - user
      operationId: fetchUsers
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: string
                required:
                  - users
